server:
  addr: 0.0.0.0
  port: 9302
  limit: 50
  burst: 100
  requestTimeout: 60s
mongo:
  addr: "mongodb://root:root@172.17.0.1:27017"
  database: "test"
  dialTimeout: "3s"
scraper:
  sina:
    info: true
    follow: false
    fans: false
    tweet:
      main: true
      comment: false
drive:
  type: chrome-remote
  addr: "ws://172.21.48.1:9222/devtools/browser"
