// Code generated by "stringer -type ErrCode -linecomment"; DO NOT EDIT.

package errcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-0]
	_ = x[DBErr-1]
	_ = x[JsonMarshal-2]
	_ = x[ServerErr-3]
	_ = x[NotFound-4]
}

const _ErrCode_name = "successdatabase operation errorjson marshall or unmarshall errorserver errornot found"

var _ErrCode_index = [...]uint8{0, 7, 31, 64, 76, 85}

func (i ErrCode) String() string {
	if i < 0 || i >= ErrCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
